changes

diff --git a/.github/workflows/tag-version.yaml b/.github/workflows/tag-version.yaml
--- a/.github/workflows/tag-version.yaml
+++ b/.github/workflows/tag-version.yaml
@@ -20,9 +20,9 @@ concurrency:
 env:
   version: ""
 
-jobs:    
-  tag_version:
-    name: Tag Version
+jobs:
+  get_version:
+    name: Get Version
     runs-on: ubuntu-latest
     steps:
       - name: Get Version from pull request
@@ -30,11 +30,96 @@ jobs:
         shell: bash
         run: |
           echo "version=$(echo "${{ github.event.pull_request.title }}" | cut -c 9-20)" >> $GITHUB_ENV
+
       - name: Get Version from Input
         if: github.event.inputs.version
         shell: bash
         run: |
-          echo "tarun"
+          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
+
       - name: echo Version
         run: |
           echo "$GITHUB_ENV"
+          echo ${{ env.version }}
+
+      - name: Check version format
+        run: |
+          if [[ ${{ steps.extract-from-pr.outputs.version }} =~ ^20[0-9][0-9]\.[0-9]\.[1-9][0-9]*$ ]]; 
+          then
+            exit 0
+          else
+            exit 1
+          fi
+          
+  tag_version:
+    name: Tag Version
+    runs-on: ubuntu-latest
+    needs: get_version
+    if: startsWith(env.version, '20')
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Check if tag already exist
+        run: |
+          if [ $(git tag -l "v${{ env.version }}") ]; then
+            echo "Tag already exists!"
+            exit 1
+          else
+            exit 0
+          fi
+
+      - name: Tag & Upload version commit
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git tag -a v${{ env.version }} -m "Version ${{ env.version }}"
+          git push origin v${{ env.version }}
+
+      - name: Extract release notes
+        id: extract-release-notes
+        uses: ffurrer2/extract-release-notes@v1
+        with:
+          changelog_file: CHANGELOG.md
+
+      - name: Create a new release
+        uses: ncipollo/release-action@v1
+        with:
+          body: ${{ steps.extract-release-notes.outputs.release_notes }}
+          tag: 'v${{env.version }}'
+          name: "Release: ${{ env.version }}"
+
+  notify:
+    name: Notify on team's channel
+    runs-on: ubuntu-latest
+    needs: tag_version
+    steps: 
+      - name: echo verison for notify
+        run: |
+          echo ${{ env.version }}
+      # - name: 📣 Send teams notification about release failure
+      #   uses: simbo/msteams-message-card-action@latest
+      #   if: ${{ failure() }} 
+      #   with:
+      #     webhook: "https://jda365.webhook.office.com/webhookb2/6366d704-047d-47bf-89bb-9b4849f802f5@2ac36cee-0617-4ac0-bebf-e1ce5dfab86c/IncomingWebhook/9f2c380bd65a4ca88e2821f6e3ff52a5/336f29b9-14a6-4ca1-977b-9c7e4881a6ad"
+      #     color: dc3545
+      #     title: Released failed for version <h2>${{ env.version }}</h2>
+      #     message: ${{ steps.extract-release-notes.outputs.release_notes }}
+      #     buttons: |
+      #       View Repo ${{ github.server_url }}/${{ github.repository }}
+      #       View Workflow ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+      # - name: 📣 Send teams notification about new Release
+      #   uses: simbo/msteams-message-card-action@latest
+      #   if: ${{ success() }}
+      #   with:
+      #     webhook: "https://jda365.webhook.office.com/webhookb2/6366d704-047d-47bf-89bb-9b4849f802f5@2ac36cee-0617-4ac0-bebf-e1ce5dfab86c/IncomingWebhook/9f2c380bd65a4ca88e2821f6e3ff52a5/336f29b9-14a6-4ca1-977b-9c7e4881a6ad"
+      #     title: Version <h2>${{ env.version }}</h2> Released
+      #     message: ${{ steps.extract-release-notes.outputs.release_notes }}
+      #     color: 28a745
+      #     buttons: |
+      #       View Repo ${{ github.server_url }}/${{ github.repository }}
+      #       View Release logs ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{env.version}}
+      #       View Workflow ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
